import type { Metadata } from "next";
import "./globals.css";
import { GithubProvider } from "../context/GithubContext";
import { CustomThemeProvider } from "../context/ThemeContext";
import { ToastContainer } from "react-toastify";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomThemeProvider>
          <GithubProvider>{children}</GithubProvider>
        </CustomThemeProvider>
          {/* <ToastContainer position="bottom-right" autoClose={3000} theme="colored" /> */}
      </body>
    </html>
  );
}
